[phases.setup]
nixPkgs = ["python311", "curl"]

[phases.install]
cmds = [
  "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python3 get-pip.py",
  "pip install -r requirements.txt"
]

[start]
cmd = "python3 event_checker.py"
