[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = [
  "python311",
  "python311Packages.setuptools",
  "python311Packages.wheel",
  "python311Packages.discordpy-self"
]

[start]
cmd = "python3 event_checker.py"
